AppBundle\Entity\Base\Person:
    type: mappedSuperclass
    table: person
    id:
        id:
            type: integer
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
            id: true
            generator:
                strategy: IDENTITY
    fields:
        birthDate:
            type: date
            scale: 0
            length: null
            unique: false
            nullable: true
            precision: 0
            column: birth_date
        familyName:
            type: string
            scale: 0
            length: null
            unique: false
            nullable: true
            precision: 0
            column: family_name
        gender:
            type: string
            scale: 0
            length: null
            unique: false
            nullable: true
            precision: 0
        name:
            type: string
            scale: 0
            length: null
            unique: false
            nullable: true
            precision: 0
    lifecycleCallbacks: {  }
