AppBundle\Entity\Order:
    type: entity
    table: order_
    repositoryClass: AppBundle\Entity\OrderRepository
    id:
        id:
            type: integer
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
            id: true
            generator:
                strategy: IDENTITY
    fields:
        status:
            type: string
            scale: 0
            length: null
            unique: false
            nullable: true
            precision: 0
        readyAt:
            type: datetime
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
            column: ready_at
        createdAt:
            type: datetime
            column: created_at
            gedmo:
                timestampable:
                    on: create
        updatedAt:
            type: datetime
            column: updated_at
            gedmo:
                timestampable:
                    on: update
        uuid:
            type: string
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
        charge:
            type: string
            scale: 0
            length: null
            unique: false
            nullable: true
            precision: 0
        totalExcludingTax:
            type: float
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
            column: total_excluding_tax
        totalTax:
            type: float
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
            column: total_tax
        totalIncludingTax:
            type: float
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
            column: total_including_tax
    manyToOne:
        customer:
            targetEntity: AppBundle\Entity\ApiUser
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                customer_id:
                    referencedColumnName: id
            orphanRemoval: false
        restaurant:
            targetEntity: AppBundle\Entity\Restaurant
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                restaurant_id:
                    referencedColumnName: id
            orphanRemoval: false
    oneToMany:
        orderedItem:
            targetEntity: AppBundle\Entity\OrderItem
            cascade:
                - all
            fetch: LAZY
            mappedBy: order
            inversedBy: null
            orphanRemoval: false
            orderBy: null
        events:
            targetEntity: AppBundle\Entity\OrderEvent
            cascade: {  }
            fetch: LAZY
            mappedBy: order
            inversedBy: null
            orphanRemoval: false
            orderBy:
                createdAt: ASC
    oneToOne:
        delivery:
            targetEntity: AppBundle\Entity\Delivery
            cascade:
                - all
            fetch: LAZY
            mappedBy: order
            inversedBy: null
            joinColumns: {  }
            orphanRemoval: false
    lifecycleCallbacks:
        prePersist:
            - prePersist
    entityListeners:
        AppBundle\Entity\Listener\OrderListener:
            prePersist:
                - prePersist
            postPersist:
                - postPersist
            postUpdate:
                - postUpdate
