AppBundle\Entity\Store:
    type: entity
    table: store
    id:
        id:
            type: integer
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            scale: 0
            length: null
            unique: false
            nullable: true
            precision: 0
        enabled:
            type: boolean
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
            options:
                default: false
        imageName:
            type: string
            scale: 0
            length: 255
            unique: false
            nullable: true
            precision: 0
            column: image_name
        website:
            type: string
            scale: 0
            length: null
            unique: false
            nullable: true
            precision: 0
        telephone:
            type: string
            scale: 0
            length: null
            unique: false
            nullable: true
            precision: 0
        createdAt:
            type: datetime
            column: created_at
            gedmo:
                timestampable:
                    on: create
        updatedAt:
            type: datetime
            column: updated_at
            gedmo:
                timestampable:
                    on: create
        legalName:
            type: string
            scale: 0
            length: null
            unique: false
            nullable: true
            precision: 0
            column: legal_name
        openingHours:
            type: json_array
            scale: 0
            length: null
            unique: false
            nullable: true
            precision: 0
            column: opening_hours
        vatID:
            type: string
            scale: 0
            length: null
            unique: false
            nullable: true
            precision: 0
            column: vat_id
        additionalProperties:
            type: json_array
            scale: 0
            length: null
            unique: false
            nullable: true
            precision: 0
            column: additional_properties
    oneToOne:
        address:
            targetEntity: AppBundle\Entity\Address
            cascade:
                - all
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                address_id:
                    referencedColumnName: id
            orphanRemoval: false
    manyToOne:
        stripeParams:
            targetEntity: AppBundle\Entity\StripeParams
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                stripe_params_id:
                    referencedColumnName: id
            orphanRemoval: false
        pricingRuleSet:
            targetEntity: AppBundle\Entity\Delivery\PricingRuleSet
            cascade:
                - persist
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                pricing_rule_set_id:
                    referencedColumnName: id
            orphanRemoval: false
    oneToMany:
        deliveries:
            targetEntity: AppBundle\Entity\Delivery
            cascade: {  }
            fetch: LAZY
            mappedBy: store
            inversedBy: null
            orphanRemoval: false
            orderBy: null
    lifecycleCallbacks: {  }
