AppBundle\Entity\StripePayment:
    type: entity
    table: stripe_payment
    uniqueConstraints:
        stripe_payment_unique:
            columns:
                - resource_class
                - resource_id
    id:
        id:
            type: integer
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
            id: true
            generator:
                strategy: IDENTITY
    fields:
        uuid:
            type: string
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
        resourceClass:
            type: string
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
            column: resource_class
        resourceId:
            type: integer
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
            column: resource_id
        status:
            type: string
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
        charge:
            type: string
            scale: 0
            length: null
            unique: false
            nullable: true
            precision: 0
        totalExcludingTax:
            type: float
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
            column: total_excluding_tax
        totalTax:
            type: float
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
            column: total_tax
        totalIncludingTax:
            type: float
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
            column: total_including_tax
    manyToOne:
        user:
            targetEntity: AppBundle\Entity\ApiUser
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                user_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks:
        prePersist:
            - prePersist
