AppBundle\Entity\Tagging:
    type: entity
    table: tagging
    uniqueConstraints:
        tagging_unique:
            columns:
                - resource_class
                - resource_id
                - tag_id
    id:
        id:
            type: integer
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
            id: true
            generator:
                strategy: IDENTITY
    fields:
        resourceClass:
            type: string
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
            column: resource_class
        resourceId:
            type: integer
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
            column: resource_id
    manyToOne:
        tag:
            targetEntity: AppBundle\Entity\Tag
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                tag_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
